// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  firebaseConfig: {
    apiKey: 'AIzaSyALz4lbPUaTD3MEAlTjcVScy2vQDC1jZYk',
    authDomain: 'ngx-rocket-d87f9.firebaseapp.com',
    projectId: 'ngx-rocket-d87f9',
    storageBucket: 'ngx-rocket-d87f9.appspot.com',
    messagingSenderId: '933389346838',
    appId: '1:933389346838:web:e8c02f4dd0ece4e6e2ed37',
    measurementId: 'G-1L39F9KJB5',
  },
};
